export const tagTypes = {
  auth: "Auth",
  user: "User",
  dashboard: "Dashboard",
  owner: "Owner",
  listing: "Listing",
  advertisement: "Advertisement",
  payment: "Payment",
  review: "Review",
  booking: "Booking",
  reportsAnalytics: "ReportsAnalytics",
  adminTeam: "AdminTeam",
  legalDocuments: "LegalDocuments",
  settings: "Settings",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.dashboard,
  tagTypes.owner,
  tagTypes.listing,
  tagTypes.advertisement,
  tagTypes.payment,
  tagTypes.review,
  tagTypes.booking,
  tagTypes.reportsAnalytics,
  tagTypes.adminTeam,
  tagTypes.legalDocuments,
  tagTypes.settings,
];
